### ISSUE TITLE
Suggested for 'plot'

### ISSUE THREAD

**Issue by dorianps** [stnava/ANTsR#19]
1. Enable adding a title to the plot.

2. Crop better the image so it doesn't plot in two rows when not necessary.

3. Fix slices='84x84x1' so it gets simply slices=84, or better slices=84:90, or slices=c(20,32,56) for multiple images.

**Comment by stnava** [comment]
also color bar ....

this simple example should also work much better

```
mni<-antsImageRead( getANTsRData("ch2") , 3 ) 
plot( mni )
```

**Comment by dorianps** [comment]
btw, just updated to latest antsr and plot now diplays stretched images.
![image](https://cloud.githubusercontent.com/assets/9083517/6642643/71dd74a6-c97c-11e4-9965-fd51ad4b0949.png)

**Comment by bkandel** [comment]
The numeric vector for specifying slices should work.  

No idea where the squished images came from.  I'll take a look at that.

**Comment by bkandel** [comment]
Squished images should be fixed now, and a basic version of colorbar works.  Still working on getting the proportions done reasonably.

**Comment by bkandel** [comment]
It is possible to add a title to both the image and colorbar now, but location is still an issue.  Automatic image cropping also works now.

**Comment by dorianps** [comment]
It's working now, thanks.

I am having an issue with images cropped to a single slice. They should appear full slice on the image, but they still appear as a raw with only a slice at the beginning. Not sure this needs a fix, the problem is cropImage and cropIndices, which produce still a 3D image even when a single slice is selected. Will post this on another issue.

**Comment by bkandel** [comment]
Another suggestion from Dorian: Separate auto-slice selector from cropping
the image, so you can have one without the other.

2015-03-14 22:42 GMT-04:00 dorianps <notifications@github.com>:

**Comment by dorianps** [comment]
1. Change plotting to stack slices in a 4:3 format instead of a single line.

2. Title and colorbar are not in correct position.

**Comment by bkandel** [comment]
Also title doesn't work at all unless colorbar is enabled.

2015-03-20 16:35 GMT-04:00 dorianps <notifications@github.com>:

**Comment by stnava** [comment]
i think most of this is addressed now.
