### ISSUE TITLE
Build on Ubuntu

### ISSUE THREAD

**Issue by jeffduda** [stnava/ANTsR#69]
Recently tried building on my laptop and had to modify Makevars as follows:

1) added additional ${itklib} to end of PKG_LIBS to avoid failure caused by undefined symbol
2a) -DVCL_CAN_STATIC_CONST_INIT_FLOAT=1 or
2b) delete CXX_STD=CXX11 from ANTsR/configure, ANTsR/src/Makevars, ITKR/configure
This was compiled using:
g++ --version
g++ (Ubuntu 4.8.4-2ubuntu1~14.04) 4.8.4

1) is probably safe to change, but I was concerned that 2) would break other builds so I didn't want to push that change. Just wanted to document the issue in case other have similar problems.

**Comment by stnava** [comment]
also reference https://github.com/stnava/ANTsR/issues/4

another alternative might be just to install/use clang - but i have not tried that on ubuntu

**Comment by stnava** [comment]
another option here would be to detect if ubuntu version is 12 ( then -DVCL_CAN_STATIC_CONST_INIT_FLOAT=0 ) or 14 ( then  -DVCL_CAN_STATIC_CONST_INIT_FLOAT=1 ) and add this to Makeovers

but not sure how to do this ... i added the extra link libraries which is fine.

**Comment by stnava** [comment]
tried a bit more to address this in the process of getting ANTsR tests on travis osx environment

https://github.com/stnava/ANTsR/blob/master/src/Makevars#L9-L20

```
UNAME := $(shell uname)

ifeq ($(UNAME), Linux)
PKG_CPPFLAGS = -I${ITK} -I${PWD} -I${myantssource}/Examples/include/ \
  -I${myantssource}/Utilities -I${myantssource}/Examples/ \
  -I${myantssource}/Tensor/ -DVCL_CAN_STATIC_CONST_INIT_FLOAT=0
endif
ifeq ($(UNAME), Darwin)
PKG_CPPFLAGS = -I${ITK} -I${PWD} -I${myantssource}/Examples/include/ \
  -I${myantssource}/Utilities -I${myantssource}/Examples/ \
  -I${myantssource}/Tensor/ -DVCL_CAN_STATIC_CONST_INIT_FLOAT=1
endif
```

technically may not be allowed according to ripley https://stat.ethz.ch/pipermail/r-devel/2012-November/065280.html ( recommendaion did not work ) but shows one way to (potentially) customize without having to use configure to create makevars on the fly (maybe the recommended way) specifically for each os.

otherwise, detect if is ubuntu 14 or greater and alter Makevars accordingly.   this would mean adding lines to Makevars that are specific for each build type (OSX, Ubuntu < 14, Ubuntu >= 14) etc.

**Comment by zarquon42b** [comment]
Clang does not work either with DVCL_CAN_STATIC_CONST_INIT_FLOAT=0 on ubuntu 14.04 (with latest ITKR). It seems that the latest ITKR version makes this flag obsolete for compiler versions that support c++11 flag. My guess would be that the compliler needs to support c++11 feature complete.
However 12.04 only supports c++0x which does not seem to do the trick. So the condition in makevars should test whether the CXX flag is c++11 or c++0x before setting DVCL_CAN_STATIC_CONST_INIT_FLOAT=0.

**Comment by zarquon42b** [comment]
I guess that precise support is only needed for travis, so maybe cheat by simply running:

```
sed -i '-DVCL_CAN_STATIC_CONST_INIT_FLOAT=1|-DVCL_CAN_STATIC_CONST_INIT_FLOAT=0|' ANTsR/src/Makevars.
```

**Comment by zarquon42b** [comment]
I added a configure script based on autoconf here: https://github.com/zarquon42b/ANTsR/tree/autoconf-test. It builds on Ubuntu 14.04, OSX Yosemite. Please have a look and if you think it suitable I will issue a pull request

**Comment by stnava** [comment]
cool - let me take a look via pull request.


brian

**Comment by zarquon42b** [comment]
OK, some stuff on travis does not work as expected, as g++ is used instead of clang for building.

**Comment by zarquon42b** [comment]
https://travis-ci.org/stnava/ANTsR/jobs/102095136#L673 shows that the correct compiler is selected for testing

https://travis-ci.org/stnava/ANTsR/jobs/102095136#L677 : for some reasons g++ is used instead of clang++

**Comment by zarquon42b** [comment]
OK, this was missing echo "CXX1X=clang++" >> ~/.R/Makevars in .travis.yml. I added it.

**Comment by zarquon42b** [comment]
While it works fine locally using gcc on ubuntu and clang on mac, travis does not seem to like it. One reason might be using an R version compiled with gcc and building a package with clang. Usually, you should stick to one toolchain. I will look into that later.

**Comment by zarquon42b** [comment]
OK, this was more complicated than anticipated. I had to write a test which flag is needed to successfully compile Atropos. And depending on the outcome, VCL_CXX_STATIC_CONST_INIT_FLOAT is substituted accoringly in Makevars.in.  It seems to work now, as travis didn't stop right away, but let's see.

**Comment by zarquon42b** [comment]
OK, now the OSX version doesn't do what was intended.

**Comment by zarquon42b** [comment]
The issue was due to a stupid typo, that took me 3 hours to find. Should be working globally now.

**Comment by zarquon42b** [comment]
OK. Officially fixed now the errors on OSX are unrelated and here you can see the checks whether to use VCL_CXX_CAN_STATIC_CONST_INIT_FLOAT=0 or 1
OSX: https://travis-ci.org/stnava/ANTsR/jobs/102341239#L1083

**Comment by jeffduda** [comment]
I think the current Makevars is setting VCL_CAN_STATIC_CONST_INIT_FLOAT to
the opposite of what is needed. For me, I need =0 on mac, and =1 on linux.

**Comment by stnava** [comment]
i just pushed stefan's trick ... try that


brian

**Comment by jeffduda** [comment]
Still fails. Not sure, but it looks like that fix only applies to travis,
so I'm still gettting =1 setting on my machine.

**Comment by zarquon42b** [comment]
@jeffduda  yes the trick is a cheat for travis only. 
I dug more into this, and it seems that ITK (in ITKR) checks whether VCL_CAN_STATIC_CONST_INIT_FLOAT=1 is supported and sets the flag accordingly. Thus, ANTsR needs to get the same settings as ITKR. My autoconf version checks for this. 
Could you please try https://github.com/zarquon42b/ANTsR/tree/autoconf-test ?

**Comment by zarquon42b** [comment]
In ITKR check the files:
```
src/itks/Modules/ThirdParty/VNL/src/vxl/core/vnl/vnl_numeric_traits.h
src/itks/Modules/ThirdParty/VNL/src/vxl/core/vnl/vnl_numeric_traits.cxx
```
src/itks/Modules/ThirdParty/VNL/src/vxl/config/cmake/config/CMakeLists.txt

**Comment by zarquon42b** [comment]
Of course you need to recompile ITKR without manually changing flags (if you did so as stated in your original post)

**Comment by jeffduda** [comment]
Right, the manual changes were on my home machine (linux). I use a mac in
lab. Trying out your version now...

**Comment by zarquon42b** [comment]
Which Mac version? Compiler?

**Comment by zarquon42b** [comment]
Do you use the latest ITKR version?

**Comment by jeffduda** [comment]
For now I'm trying fully clean installs of latest commits


clang++ --version

Apple LLVM version 6.0 (clang-600.0.57) (based on LLVM 3.5svn)

Target: x86_64-apple-darwin13.4.0

Thread model: posix

**Comment by zarquon42b** [comment]
There is also a bunch of other necessary (like the support of constexpr) compiler tests from ITK which are saved in ```~/R/x86_64-pc-linux-gnu-library/3.2/ITKR/libs/include/ITK-4.9/vcl_config_compiler.h``` line 148ff.
If necessary we could include this in the autoconf version, too by including the header and checking for the defines and then generating src/Makevars accordingly.

**Comment by jeffduda** [comment]
appears to be working, i.e. didn't fail immediately

**Comment by zarquon42b** [comment]
During training, I just had an idea: maybe including vcl_config_compiler.h in ants.h (from upstream ants) could fix the problem as it takes care of the appropriate defines and we would not need autoconf at all and remove the VCL_CAN_STATIC_CONST_INIT_FLOAT=1 flag from Makevars . As I am already at home with my family (European time), you could check this.
 As I am already at home with my family (European time), could you check if this would work as well?

**Comment by jeffduda** [comment]
I couldn't get that to work, but it's possible I was doing something wrong.

**Comment by stnava** [comment]
here is another (related) idea .... how about we add a function to ITKR
that will return the correct CPPFLAGS?

e.g.

PKG_CPPFLAGS = `$(R_HOME)/bin/Rscript -e 'ITKR:::itkCPPFLAGS()'`



brian

**Comment by jeffduda** [comment]
ITKR::itkCompileFlags() exists, but it looks like it isn't used

**Comment by zarquon42b** [comment]
It is rather the #defines than the actual compile flags. Because the #defines are stored in the header files that is included during compilation not manifesting itself in flags.

**Comment by stnava** [comment]
right - but, within ITKR, we can more readily interrogate the existing
build flags ( in src/itkb ) and then return the correct ones.

what i don't know is what to interrogate, specifically.


brian

**Comment by jeffduda** [comment]
Maybe this:

cat ITKR/src/itkb/Modules/ThirdParty/VNL/src/vxl/vcl/vcl_config_compiler.h
| grep VCL_CAN_STATIC_CONST_INIT_FLOAT

**Comment by stnava** [comment]
on osx, this gives:

# define VCL_CAN_STATIC_CONST_INIT_FLOAT 0


​on linux, this gives:

# define VCL_CAN_STATIC_CONST_INIT_FLOAT
​1



​but i compile with 0 on linux and 1 on OS X  ... anyway, worth a try to
base the flag off reading this info

**Comment by jeffduda** [comment]
huh, for me, those are correct. 0 on OXS, 1 on Linux

**Comment by zarquon42b** [comment]
Can you try if it works when removing DVCL_CAN_STATIC_CONST_INIT_FLOAT from Makevars at all?

**Comment by zarquon42b** [comment]
As ITK 4.9 seems to have introduced these tests the manual setting should be obsolete, however, ANTsR and ITKR need to be compiled on the same machine. So compiling ITKR one one (e.g. not supporting static const init float) and ANTsR on another based on said ITKR will fail.

**Comment by stnava** [comment]
compiling consistently is (obviously) the key to getting the osx
builds/binaries working on travis. i.e. just building ITKR and ANTsR
consistently on the travis architecture.  this will be helpful for
improving binary (and other) releases.

my latest attempt uses ifeq(CC,CLANG) to set the DVCL=1 flag ... otherwise,
it remains absent.  seems to work for travis and the two variants of linux
that i've tried.  i.e. nothing breaks.

**Comment by stnava** [comment]
and finally:  https://github.com/stnava/manageReleases  will make it easier
for us ... might also add some versioning to the scripts that will update
the code in the appropriate places when we want to increment.


brian

**Comment by zarquon42b** [comment]
OK, I tested different things on different machines and the only thing working in all cases was the autoconf-test branch.

**Comment by zarquon42b** [comment]
No, autoconf-test did not work on Precise vanilla in my VM. While current master fails on my Yosemite VM because the variable CC is usually not set as environment variable (except in travis)

**Comment by stnava** [comment]
ok - went to:

```
ifneq ($(UNAME), Linux)
PKG_CPPFLAGS = -I${ITK} -I${PWD} -I${myantssource}/Examples/include/ \
  -I${myantssource}/Utilities -I${myantssource}/Examples/ \
  -I${myantssource}/Tensor/ -DVCL_CAN_STATIC_CONST_INIT_FLOAT=1
endif
```

as UNAME is not defined (by default) in OSX either.

potential solutions are currently:

(1)  this: ifneq ($(UNAME), Linux)   ---- simple but fragile and not cran compliant [here](https://github.com/stnava/ANTsR/commit/59271db12946a1b5e30baa423b2afd75cc2c93c6)

(2)  autoconf  --- complex but cran compliant ... heavyweight, may set too high a bar for "casual coders" or contributors to this project [here](https://github.com/stnava/ANTsR/pull/70)

(3)  use Makevars.in and configure ( similar to a lightweight autoconf )  would improve over (1) ( but be similar and more flexible ) and probably cran compliant ... could be extended with new/better solutions.  example [here](https://github.com/stnava/ANTsR/commit/84bc609b079bbcbf2057ff2bee55e94a0149f732)

guess i prefer the last one at the moment.

**Comment by stnava** [comment]
this last experiment was helpful ... seems that basically, need to detect if clang is the compiler as previously expected.  but in bash rather than Makevars ... issues are that gcc in osx points to clang and that CC may not be defined (esp on osx, it seems) ... so these (superficial/band-aid) checks need to cover these cases.

**Comment by stnava** [comment]
[this commit](https://github.com/stnava/ANTsR/commit/0355fc073a287fdea08cf0249a7aa583ce8d1a2e)

**Comment by stnava** [comment]
@jeffduda - current version work for you?

**Comment by jeffduda** [comment]
Works on my mac, will test on Ubuntu tonight when I get home.

**Comment by jeffduda** [comment]
Now working on all of my machines.

**Comment by zarquon42b** [comment]
Nice! the only versions it does not work are outdated gcc  and clang versions, but can neglect those. Cool that it is fixed now.

**Comment by stnava** [comment]
thanks to both of you guys for contributing to this (probably temporary) fix ... @zarquon42b :  i'd like to know how to use autoconf in ANTsR and would like to store this effort in a separate branch, in case it is needed again.  would you mind updating your autoconf-branch with latest master?  i'd like to merge that into the main ANTsR repo ( keeping it as autoconf-branch )  ... am sure it will come in handy again.

**Comment by zarquon42b** [comment]
Could you create a branch in your repo I can create a pull request to? I cannot send a pull request to a non existing branch.

**Comment by stnava** [comment]
here it is: https://github.com/stnava/ANTsR/tree/autoconf-test
