### ISSUE TITLE
ANTsR antsRegistration command with SyNBold

### ISSUE THREAD

**Issue by BrysonBR** [stnava/ANTsR#71]
I am trying to register my BOLD images to the subject's T1 image.
I called the following three lines:
> moving<-antsImageRead("BOLD.nii.gz")
> fixed<-antsImageRead("T1_Brain.nii.gz")
> antsRegistration(fixed=fixed, moving=moving, typeofTransform="SyNBold")

And received this error:
    Exception Object caught: 
    
    itk::ExceptionObject (0x7ff7b6e038c8)
    Location: "unknown" 
    File: /usr/local/lib/R/3.2/site-library/ITKR/libs/include/ITK-4.9/itkImageMomentsCalculator.hxx
    Line: 156
    Description: itk::ERROR: ImageMomentsCalculator(0x7ff7b6e03630): Compute(): Total Mass of the image was zero. Aborting here to prevent division by zero later on.
    
    
    $warpedmovout
    antsImage
      Pixel Type          : float 
      Components Per Pixel: 1 
      Dimensions          : 176x256x256 
      Voxel Spacing       : 1x0.9765625x0.976562440395355 
      Origin              : 91.01056 107.6796 -135.8272 
      Direction           : -0.9990482 0 -0.04361939 0 -1 0 -0.04361939 0 0.9990482 
    
    
    $warpedfixout
    antsImage
      Pixel Type          : float 
      Components Per Pixel: 1 
      Dimensions          : 64x64x44x470 
      Voxel Spacing       : 3x3x3.75x1 
      Origin              : -95.88672 85.799 -73.52123 0 
      Direction           : 0.9990482 1.726682e-05 0.04362019 0 -2.511333e-08 -0.9999999 0.0003964198 0 -0.04362019 0.0003960436 0.9990481 0 0 0 0 1 
    
    
    $fwdtransforms
    [1] "/var/folders/0b/8wcfvfbd0dn4ljdrtqp_6zfh0000gp/T//RtmpdtrQ6M/file26be3e2040f1Warp.nii.gz"      
    [2] "/var/folders/0b/8wcfvfbd0dn4ljdrtqp_6zfh0000gp/T//RtmpdtrQ6M/file26be3e2040f0GenericAffine.mat"
    
    $invtransforms
    [1] "/var/folders/0b/8wcfvfbd0dn4ljdrtqp_6zfh0000gp/T//RtmpdtrQ6M/file26be3e2040f0GenericAffine.mat" 
    [2] "/var/folders/0b/8wcfvfbd0dn4ljdrtqp_6zfh0000gp/T//RtmpdtrQ6M/file26be3e2040f1InverseWarp.nii.gz"

The files that I used are in here:
https://drive.google.com/file/d/0B9oWACI5TJOEeU9hRUVLWDFXUkk/view?usp=sharing
https://drive.google.com/file/d/0B9oWACI5TJOEY2pxNWpOS3ZseEk/view?usp=sharing

Am I doing something wrong?

**Comment by jeffduda** [comment]
The folder does not seem to readable. It looks like one of your images is
all zeros. Try doing a sum() or sum(abs()) on each to make sure there are
non-zero values.

**Comment by BrysonBR** [comment]
I've updated the google drive links, so they should be working now. Both of the images look fine to me (i.e. not all zeros), which is why I'm confused.

**Comment by BrysonBR** [comment]
Here's the results from sum()
```
> sum(fixed)
[1] 204870944
> sum(moving)
[1] 26112405408
```

**Comment by jeffduda** [comment]
Still can't access the folder for some reason. The problem may be that you
seem to be trying to register a 4D image to a 3D image so possibly the
first time point of the BOLD image is all zeros. Try:

meanbold <- apply.antsImage(moving, c(1,2,3), mean)
antsRegistration(fixed=fixed, moving=meanbold, typeofTransform="SyNBold")

**Comment by BrysonBR** [comment]
Jeff,
   That seems to be working. I assumed (evidently incorrectly) that the SyNBold would work with 4D images. But I guess I should transform the BOLD_avg to the T1 and then apply that transform to the entire BOLD sequence later. Thanks for your help!

**Comment by stnava** [comment]
the function option is admittedly poorly named.  it's just a rigid registration followed by a syn registration of ND to ND images.
